### ISSUE TITLE
Add Provider testing functionality

### ISSUE THREAD

**Issue by kayvonghaffari** [payout/rester#28]
Now that we can create stubs to validate tests from the client side, we need a way for a Service (Provider) to validate that the stubs created by the client are valid.

For example, the Service needs to check that a request with those parameters do, in fact, respond with the correct response code and body specified in the stub:

```yml

/v1/cards:
  POST:
    With valid card details:
      request:
        body:
         card_number: "4111111111111111",
         exp_month: "08",
         exp_year: "2017"
      response:
        code: 200
        body:
          token: "CTABCDEFG",
          exp_month: "08",
          exp_year: "2017",
          status: "ready"
```
