### ISSUE TITLE
Remove 'code' from the response in contract

### ISSUE THREAD

**Issue by kayvonghaffari** [payout/rester#42]
Instead, specify whether the request was successful or not (default will be `true`)
```yml
/v1/accounts:
  POST:
    Context:
      request:
        key: value
      response[successful=false]:
        account_id: 1234
```

Can use this regex to pull out the response parameters:
```ruby
/\Aresponse(\[(\w+)=(\w+)(,(\w+)=(\w+))*\])?\z/
```
