### ISSUE TITLE
Stringify all values in stub requests when comparing

### ISSUE THREAD

**Issue by roberthoner** [payout/rester#47]
When making requests, all values are strings.  However, in a stub, the request values can be numbers and booleans.

For example:
```yml
request:
  bool: true
  number: 1234
  string: some string here
```

This forces the stub author to ensure that everything is a string:
```yml
request:
  bool: 'true'
  number: '1234'
  string: some string here
```

Instead, it would simplify writing the stubs if the StubAdapter automatically converted all request values to strings, so it's less picky.
