### ISSUE TITLE
Process stub files as ERBs

### ISSUE THREAD

**Issue by roberthoner** [payout/rester#48]
Stub files should support ERB syntax.  This will allow us to create more dynamic stubs.

For example, you could specify a card that always expires in a year from now:
```yml
/v1/cards:
  POST:
    With expiration 1 year from now:
      request:
        number: 4111111111111111
        exp_month: <%= DateTime.now.month %>
        exp_year: <%= DateTime.now.year + 1 %>
```

**Comment by roberthoner** [comment]
Downside here is we're locking into ruby a little bit.  In the future we may have a java version of rester that will need to interface with ruby consumers and producers.  That will force the java library to deal with evaluating ERB, which we may not want to do.

Also, although we can't have dynamic values in stock YAML, we do have the ability to reference other nodes, so we can create values and reference them throughout our file.

For example:
```yml
/v1/cards:
  POST:
    With valid data:
      request: &valid_tokenization_request
        number: 4111111111111111
        exp_month: 10
        exp_year: 2020
      response:
        token: SomeToken
        status: valid

    With invalid card number:
      request:
        <<: *valid_tokenization_request
        number: 1234123412341234
      response[successful=false]:
        error: invalid card number
```
